# ============================================================================
# REFERENCE ONLY - Do not edit this file!
# ============================================================================
# This is a reference template. Create your actual module at:
#   terraform-course/modules/s3-bucket/outputs.tf
#
# See the README.md for the step-by-step walkthrough.
# ============================================================================

# S3 Bucket Module - Outputs
# Expose useful values from your module

# TODO: Define the following outputs at terraform-course/modules/s3-bucket/:
# - bucket_id (the bucket name/ID)
# - bucket_arn (the bucket ARN)
# - bucket_region (the bucket region)

# Example structure:
# output "bucket_id" {
#   description = "The name of the bucket"
#   value       = aws_s3_bucket.this.id
# }
#
# output "bucket_arn" {
#   description = "The ARN of the bucket"
#   value       = aws_s3_bucket.this.arn
# }
#
# output "bucket_region" {
#   description = "The AWS region of the bucket"
#   value       = aws_s3_bucket.this.region
# }
