# ============================================================================
# REFERENCE ONLY - Do not edit this file!
# ============================================================================
# This is a reference template. Create your actual module at:
#   terraform-course/modules/s3-bucket/variables.tf
#
# See the README.md for the step-by-step walkthrough.
# ============================================================================

# S3 Bucket Module - Variables
# Define the inputs your module accepts

# TODO: Define the following variables at terraform-course/modules/s3-bucket/:
# - bucket_name (string, required) with validation for length >= 3
# - environment (string, required) with validation for dev/staging/prod
# - enable_versioning (bool, optional, default: true)
# - tags (map(string), optional, default: {})

# Example structure:
# variable "bucket_name" {
#   description = "Base name for the S3 bucket"
#   type        = string
#
#   validation {
#     condition     = length(var.bucket_name) >= 3 && length(var.bucket_name) <= 63
#     error_message = "Bucket name must be between 3 and 63 characters."
#   }
# }
